"""empty message

Revision ID: 517b5ea34274
Revises: d777731b8254
Create Date: 2021-10-05 15:47:40.559027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517b5ea34274'
down_revision = 'd777731b8254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bets', sa.Column('active_wager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bets', 'active_wager')
    # ### end Alembic commands ###
