"""empty message

Revision ID: 74aecea38558
Revises: a904f26c5da7
Create Date: 2021-10-05 14:19:09.711615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74aecea38558'
down_revision = 'a904f26c5da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'authors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'user_id')
    # ### end Alembic commands ###
